apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: event
  labels:
    app: auth-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth
          image: om6214/auth-svc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              name: http
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: app-secret
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
