apiVersion: v1
kind: ConfigMap
metadata:
  name: event-config
  namespace: event
data:
  NODE_ENV: "production"
  PORT: "3002"
  MONGO_DATABASE: "event_events_db"
  AUTH_SERVICE_URL: "http://auth-svc:3001"
  BOOKING_SERVICE_URL: "http://booking-svc:3003"
